"""empty message

Revision ID: 0596784ba576
Revises: 3c6a7a83698a
Create Date: 2020-12-28 17:00:02.460766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0596784ba576'
down_revision = '3c6a7a83698a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('message_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'message_type')
    # ### end Alembic commands ###
