"""empty message

Revision ID: 10cec9515039
Revises: d42c524a700c
Create Date: 2020-12-27 18:33:27.847334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cec9515039'
down_revision = 'd42c524a700c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_available_lot', 'lots_available')
    op.drop_column('heavy_vehicle_available_lot', 'lots_available')
    op.drop_column('motor_bike_available_lot', 'lots_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motor_bike_available_lot', sa.Column('lots_available', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('heavy_vehicle_available_lot', sa.Column('lots_available', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('car_available_lot', sa.Column('lots_available', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
