"""empty message

Revision ID: 2425abece127
Revises: 10cec9515039
Create Date: 2020-12-27 18:34:01.028801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2425abece127'
down_revision = '10cec9515039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_available_lot', sa.Column('lots_available', sa.Integer(), nullable=True))
    op.add_column('heavy_vehicle_available_lot', sa.Column('lots_available', sa.Integer(), nullable=True))
    op.add_column('motor_bike_available_lot', sa.Column('lots_available', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motor_bike_available_lot', 'lots_available')
    op.drop_column('heavy_vehicle_available_lot', 'lots_available')
    op.drop_column('car_available_lot', 'lots_available')
    # ### end Alembic commands ###
