"""empty message

Revision ID: 66330d170154
Revises: d939013d961b
Create Date: 2020-12-27 01:57:59.531469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66330d170154'
down_revision = 'd939013d961b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_carpark_info', sa.Column('park_capacity', sa.Integer(), nullable=True))
    op.drop_column('car_carpark_info', 'parkCapacity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_carpark_info', sa.Column('parkCapacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('car_carpark_info', 'park_capacity')
    # ### end Alembic commands ###
