"""empty message

Revision ID: 8524d66f4857
Revises: 14396662f043
Create Date: 2021-01-02 23:40:05.193755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8524d66f4857'
down_revision = '14396662f043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_system_response', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_system_response', 'user_info', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_system_response', type_='foreignkey')
    op.drop_column('user_system_response', 'user_id')
    # ### end Alembic commands ###
