"""empty message

Revision ID: 943d2af1e300
Revises: 995b94206ca7
Create Date: 2020-12-29 01:50:06.337132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '943d2af1e300'
down_revision = '995b94206ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_system_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('message_body', sa.String(length=200), nullable=True),
    sa.Column('response_server', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('reponse_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_message_id'], ['user_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_system_response')
    # ### end Alembic commands ###
