"""empty message

Revision ID: 995b94206ca7
Revises: e69d0f332b63
Create Date: 2020-12-28 20:28:28.206959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995b94206ca7'
down_revision = 'e69d0f332b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('username', sa.String(length=124), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'username')
    # ### end Alembic commands ###
