"""empty message

Revision ID: d42c524a700c
Revises: 66330d170154
Create Date: 2020-12-27 03:03:31.778596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42c524a700c'
down_revision = '66330d170154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heavy_vehicle_carpark_info', sa.Column('park_capacity', sa.Integer(), nullable=True))
    op.drop_column('heavy_vehicle_carpark_info', 'parkCapacity')
    op.add_column('motor_bike_carpark_info', sa.Column('park_capacity', sa.Integer(), nullable=True))
    op.drop_column('motor_bike_carpark_info', 'parkCapacity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motor_bike_carpark_info', sa.Column('parkCapacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('motor_bike_carpark_info', 'park_capacity')
    op.add_column('heavy_vehicle_carpark_info', sa.Column('parkCapacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('heavy_vehicle_carpark_info', 'park_capacity')
    # ### end Alembic commands ###
