"""empty message

Revision ID: d939013d961b
Revises: fae13efd1a12
Create Date: 2020-12-27 00:05:55.660807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd939013d961b'
down_revision = 'fae13efd1a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_token')
    # ### end Alembic commands ###
