"""empty message

Revision ID: f3f93dc7a5df
Revises: 807f88c16091
Create Date: 2020-12-26 23:40:10.372389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f93dc7a5df'
down_revision = '807f88c16091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heavy_vehicle_carpark_main_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pp_code', sa.String(length=20), nullable=True),
    sa.Column('pp_name', sa.String(length=124), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heavy_vehicle_carpark_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_table_id', sa.Integer(), nullable=False),
    sa.Column('svy21_coordinates', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['main_table_id'], ['heavy_vehicle_carpark_main_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heavy_vehicle_carpark_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_table_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('weekday_rate', sa.String(length=20), nullable=True),
    sa.Column('weekday_min', sa.String(length=20), nullable=True),
    sa.Column('satday_rate', sa.String(length=20), nullable=True),
    sa.Column('satday_min', sa.String(length=20), nullable=True),
    sa.Column('sun_ph_rate', sa.String(length=20), nullable=True),
    sa.Column('sun_ph_min', sa.String(length=20), nullable=True),
    sa.Column('parking_system', sa.String(length=20), nullable=True),
    sa.Column('parkCapacity', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=124), nullable=True),
    sa.ForeignKeyConstraint(['main_table_id'], ['heavy_vehicle_carpark_main_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heavy_vehicle_carpark_info')
    op.drop_table('heavy_vehicle_carpark_geometry')
    op.drop_table('heavy_vehicle_carpark_main_table')
    # ### end Alembic commands ###
